### ISSUE TITLE
[angular2-redux-starter] ApplicationRef.tick is called recursively

### ISSUE THREAD

**Issue by barretodavid** [rangle/rangle-starter#100]
Right after installing the `angular2-redux-starter` using the npm package `rangle-starter` and trying to login to the app using the credentials "user" and "pass", I see an error in the browser console (Chrome - OSX):

```
EXCEPTION: ApplicationRef.tick is called recursively
```

**Comment by SethDavenport** [comment]
Rolling back heroku to the previous deployment fixes the issue.  That suggests this was introduced by the recent 'split-path-by-plugin' change.

I think what's happening is that the shims and polyfills are now loaded after vendor.js, whereas they used to be included in it.

The shims and polyfills need to be loaded _before_ angular for it to work correctly.

One approach might be to put this in index.ts (before anything else):

``` typescript
import 'es6-promise';
import 'es5-shim';
import './ie-shims';

// Importing this one might be a little interesting since it's pre bundled.
import 'angular2/polyfills';
```

Otherwise we need to figure out how to get webpack to let us specify an injection order.

**Comment by SethDavenport** [comment]
Worst case senario we can roll back the splitbypath plugin work; however I'd like us to try and get it working first.

**Comment by codebyuma** [comment]
I'm investigating now.

**Comment by codebyuma** [comment]
Importing the shims and polyfills in index.ts before angular seems to resolve the issue. PR is open.

The other starters seem to be fine right now but I can update them as well to be consistent. Thoughts? @SethDavenport

**Comment by SethDavenport** [comment]
It affects http://angular2-starter-rangle.herokuapp.com too - navigate to the about page and back.

**Comment by SethDavenport** [comment]
But yeah consistency is good so let's make all the starters follow the pattern.

**Comment by codebyuma** [comment]
Good catch! Ok, PR is open for angular2-starter: https://github.com/rangle/angular2-starter/pull/22  

I'll update the others now, just to be consistent.
