### ISSUE TITLE
Add http-based authentication to remaining starters

### ISSUE THREAD

**Issue by codebyuma** [rangle/rangle-starter#107]
Similar to https://github.com/rangle/rangle-starter/issues/91

**Comment by codebyuma** [comment]
I'm starting with the angular2-redux-starter

**Comment by codebyuma** [comment]
I have it working on angular2-redux-starter now. Just want to set up tests for the new auth and server services before making the PR.

**Comment by codebyuma** [comment]
Update: Going to make a PR for this change in a moment and put the creation of tests for the server service and auth service for angular2-redux-starter into a separate issue/card as it's taking longer than expected.

**Comment by codebyuma** [comment]
@SethDavenport Hey Seth, is there a reason why the angular2-starter doesn't have the login functionality at all?

**Comment by SethDavenport** [comment]
Yeah it's intended to be a minimal starter without redux or a complex starter app. So we've trimmed the functionality; I wouldn't worry about it.

**Comment by SethDavenport** [comment]
@codebyuma : I'm seeing some console warnings when I run `npm start`:

``` sh
express-session deprecated undefined resave option; provide resave option server/node-server.js:38:9
express-session deprecated undefined saveUninitialized option; provide saveUninitialized option server/node-server.js:38:9
Warning: connect.session() MemoryStore is not
designed for a production environment, as it will leak
memory, and will not scale past a single process.
```

Seems to be related to expressSession not being set up with a production-ready store (a DB, redis, etc).  However since the app doesn't really need sessions I'm wondering if we can just not use them for now?

I'd rather not have the starters contain something that will actually blow up in production: projects needing sessions should plan out how they specifically want to store them.

Thoughts?

**Comment by codebyuma** [comment]
@SethDavenport Yes, that makes sense. We added it because the docs for Passport indicated that we needed it but I did a quick check and it seems to work without it. I'll remove from the various starters this morning and make PRs.

**Comment by codebyuma** [comment]
I also removed Express sessions from https://github.com/rangle/react-redux-starter/issues/172 before merging.
