### ISSUE TITLE
Investigate Angular 2 CLI

### ISSUE THREAD

**Issue by codebyuma** [rangle/rangle-starter#115]
https://github.com/angular/angular-cli

**Comment by codebyuma** [comment]
Just adding this video as a resource too: https://www.youtube.com/watch?v=wHZe6gGI5RY

**Comment by SethDavenport** [comment]
Thanks for logging this @codebyuma .

The main questions I'd like to answer are:
1. how does the CLI generated toolchain compare to our webpack setup, specifically in terms of:
   a. production bundle size?
   b. dev mode developer experience?
   c. unit test runner?
   d. ability to measure unit test coverage?
2. how does it bundle assets for prod? Do we get a proper minified JS bundle (good) or a ton of async module requests for each source file (bad)?
3. How much of our starter does it make obsolete?
4. Can we use it instead of our ng2 webpack setup but still retain our integration points with other tools (circleCI, heroku, etc.)

**Comment by codebyuma** [comment]
Unfortunately, I didn't get to dig into your questions last week. I looked at the basic set-up and commands while helping with the  first pass of the CLI chapter for the ng2course but didn't get to investigate customization options or compare to our current setup.

That said, as you saw, the five step  process to install third party libraries isn't fun: https://github.com/angular/angular-cli/wiki/3rd-party-libs

Running the default ng build command seems to transpile the code but in lots of single files. It doesn't create one minified JS bundle. 

Also, I couldn't easily see how to modify it to use our tools and configuration settings. Even something as simple as changing the default port - you can add a --port flag when you run the serve command but I'm not sure how to make that the actual default setting without going in and changing the ember-cli file here `node_modules/angular-cli/node_modules/ember-cli/commands/serve.js`

That said, maybe I missed something obvious... Removing myself from this card so someone else can take a look this week.

**Comment by SethDavenport** [comment]
Thanks for looking into it @codebyuma . The CLI is something to keep an eye on but it looks a little raw yet for our purposes. There are a lot of good discussions happening in the repo though:

How to use PostCSS with it:
https://github.com/angular/angular-cli/issues/634#issuecomment-220831983

Community interest in webpack (something we might be able to help with):
https://github.com/angular/angular-cli/issues/909

Watching the repo for now; we'll take the plunge when the time is right.

**Comment by dancancro** [comment]
@codebyuma  I maintain a database of the features of technologies so people can easily compare things. I just added angular2-redux-starter yesterday and as I learn it better I will be refining its information, but you can have a look at the comparison here. Just enter angular-cli into one box and angular2-redux-starter into the other, or any other pair of technologies. Then click side-by-side

http://www.techtradeoffs.info

If you see any errors, you can note them too and I'll update the data.

**Comment by mikeumus** [comment]
### Considering becoming an Angular CLI template or using @ngtools/webpack

With the Angular CLI becoming so powerful and central to workflow, it's a good time to consider if this starter makes sense to work as an Angular CLI template. See "[App Creation Using Template](https://github.com/angular/angular-cli/wiki/Stories#app-creation-using-template)" in the CLI wiki. Becoming a template would look something like this for a user to get started:

`ng new my-ng2-app --template=angular2-rangle-starter`

Or adopting [`@ngtools/webpack`](https://www.npmjs.com/~ngtools) to not miss out on any of the innovations happening on the CLI like "code splitting" (see below) and other optimizations. 

See the benefits and ability to use `@ngtools/webpack` standalone from the Angular CLI as presented in [Stephen Fluin's Angular CLI talk](https://youtu.be/uBRK6cTr4Vk?t=6m45s) at Angular Connect 2016:
- Compiles SCSS/LESS
- TypeScript transpilation
- Bundles JavaScript, CSS
- Asset optimization
- Virtual filesystem for assets
  - For serving local assets and compile versions.
- Live-reload via websockets
- Code splitting
  - Recognizing the use of loadChildren in the router, and bundling those modules separately so that any dependencies of those modules are not going to be loaded as part of your main bundle. These separate bundles will be pulled out of the critical path of your application, making your total application bundle much smaller and loading it much more performant.

**Comment by SethDavenport** [comment]
We've looked quite a bit at angular-cli, several times. While I'm a big fan of the new webpack version, it's just not flexible enough for us yet.

In particular:
- it doesn't support our CSSNext-based workflow
- it's philosophy of hiding the build configs is not one we share - as people who maintain high scale production systems we need full control, not another level of hidden detail.

Note that most of the things you mention above are available by using and understanding `webpack-dev-server` and `webpack`. In short; angular-cli is tuned for certain use cases, but rangle/angular2-starter remains a better fit for our internal needs right now.

Rest assured we're keeping an eye on it though.
