### ISSUE TITLE
ts-react: Why is server code not Typescript?

### ISSUE THREAD

**Issue by mikecann** [rangle/rangle-starter#120]
Hi,

I love the look at your typescript-react-redux-starter, it looks like its exactly what I was looking for in that it seems to solve many of the issues I am having with getting started.

What I was wondering tho is why is the server code alll Javascript and not Typescript too?

Cheers,
Mike

P.S. Not sure how to add a label to this so putting in the title instead.

**Comment by SethDavenport** [comment]
Heh. Because I'm allergic to transpiling on the backend - there's a small part of me that still doesn't quite trust it in a server environment.

That said I've been messing around with isomorphic stuff more and more so I'm starting to warm up to the idea.  Feel like making a PR? ;)

(for typescript, not for isomorphism)

**Comment by mikecann** [comment]
lol okay no worries, if I do some work in this area ill definitely do a PR!
