### ISSUE TITLE
Improve typescript source map support

### ISSUE THREAD

**Issue by SethDavenport** [rangle/rangle-starter#126]
It should be possible to debug in the browser from the TypeScript source using source maps.

However our config isn't quite right.

**Comment by SethDavenport** [comment]
@clbond has figured it out for the ng2-minimal starter.

**Comment by SethDavenport** [comment]
@alexs you might be interested in this.

**Comment by clbond** [comment]
OK, this has been done in all of the TypeScript-based starters. The last PR remaining to be merged is at https://github.com/rangle/typescript-react-redux-starter/pull/146 - I am waiting for someone to review it before I merge since it's a more complicated change than the ones I did in the angular2 repos. Once that last PR is merged I think we can close this ticket.

**Comment by SethDavenport** [comment]
@clbond - thanks! 

Did you do the angular 1 + typscript starter as well? https://github.com/rangle/angular-redux-starter

**Comment by clbond** [comment]
Ah, no, I'm sorry - I missed that one. Didn't realize there was another TS
starter. Will do first thing in the morning.

**Comment by clbond** [comment]
OK, angular-redux-starter is done now too. Implemented in https://github.com/rangle/angular-redux-starter/pull/135
