### ISSUE TITLE
Test Runner for Server ( React Redux Starter )

### ISSUE THREAD

**Issue by TrevorMills** [rangle/rangle-starter#153]
Hi there,

I've been playing around with the React Redux Starter repo as an introduction to that stack. I'm at the point where I want to write some tests on server side code, but it appears Karma doesn't know how to run tests within the ./server directory.  Is this intentional?  If you were going to add some testing boilerplate for testing server side code, what might it look like?  

Many thanks
Trevor

**Comment by rbrander** [comment]
@TrevorMills The tests are designed to be found in the src/ folder, and thus why your tests in server/ are not being found and executed.  You could move your server code to the src folder, or perhaps just your tests.  Alternatively, you could modify the karma.config.js file to include your server path in the regular expression that it uses for finding tests.

Since your issue was opened a while ago, you might be interested in knowing that we've now updated our React/Redux started package.
