### ISSUE TITLE
Installing other modules

### ISSUE THREAD

**Issue by srfoster** [rangle/rangle-starter#161]
Probably a nooby question here.  I'm using the redux-react-typescript starter.  Things work well, except... how do I install other node modules?

I assume I should just be able to do "npm install _____" and then reference the module in my code with an import.  E.g.

```
npm install animated
```

And then

```
import Animated from "animated"
```

But the webpack dev server tells me:

```
Cannot find module 'animated'
```

...even though the module exists in node_modules.  I assume that either I am missing something obvious about node (this is my first node project).  Or there is something different about the Rangle Starter stack.  Any help is appreciated.

**Comment by srfoster** [comment]
This seemed to work:

```
var Animated = require("animated") 
```

I'll admit, as a newcomer to node, I'm confused about when to use import and when to use require.

**Comment by SethDavenport** [comment]
You've run into one of the joys of Typescript :)

Typescript is great and I like it a lot. However, it does subtly change the meaning of `import` from ES6.

Essentially, typescript wants to find type definitions for the third party library, for static analysis, code completion, etc.  This presents an issue for libraries that weren't written in typescript.  So that this point you have a couple of options:

1) do a 'require' as you have done, bypassing typescript's search for 3rdparty typings. This effectively gives you a handle to the lib with type `any`. Or:
2) see if there are community-provided type definitions for that lib. 

There is a fairly active community of typescript users who take it upon themselves to supply typings for popular libs. These definitions can be obtained and managed using the [`typings` tool](https://github.com/typings/typings) which is already included in the project.

However it doesn't appear that 'animated' has community typings.  So the `require` solution you have implemented is the way to go for this particular lib.

**Comment by srfoster** [comment]
Cool!  Thanks for the clear explanation.  :)  And thanks for putting together a great starter stack.
