### ISSUE TITLE
Add a Rollup branch

### ISSUE THREAD

**Issue by marcandrews** [rangle/rangle-starter#197]
Add a branch that uses Rollup instead of Webpack

**Comment by rbrander** [comment]
@marcandrews I looked into using Rollup and I believe that it wouldn't be the right approach for our starters.  The reason being is that most of the unique features that Rollup brings, are now already features of webpack 2.  Also, Rollup is typically recommended for building libraries instead of Apps; and our starters are designed for building applications.

Please review this document out-lining the differences between Rollup and Webpack: https://medium.com/webpack/webpack-and-rollup-the-same-but-different-a41ad427058c

If you'd like, you could fork this repo and provide a pull-request of your suggested changes for review.

**Comment by marcandrews** [comment]
I opened this issue when we were still fighting with bundle sizes. It seems as though lazy-loading and SSR has come a long way so, with respect to bundle sizes and initial load times, perhaps tree-shaking is no longer the "holy grail" it once was depicted to be.
