### ISSUE TITLE
Change [chunkhash] to [hash]-[id]

### ISSUE THREAD

**Issue by troyt-42** [rangle/rangle-starter#199]
Using [chunkhash] causes errores when `npm run dev`:
```
ERROR in chunk app [entry]
[name].[chunkhash].js
Cannot use [chunkhash] for chunk in '[name].[chunkhash].js' (use [hash] instead)

ERROR in chunk vendor [entry]
[name].[chunkhash].js
Cannot use [chunkhash] for chunk in '[name].[chunkhash].js' (use [hash] instead)
```
and I think [hash]-[id] has the same effect of [chunkhash].

**Comment by SethDavenport** [comment]
@smithad15 thoughts?

**Comment by smithad15** [comment]
`[hash]-[id]` does not give the same effect since `[hash]` is the hash of the _compilation_ while `[chunkhash]` is the hash of that _specific chunk file_. 

Upon investigation it looks like it is a problem with `webpack-dev-server --hot`. It is suggested to only do hashes in production builds, not dev builds. Probably a good idea since hash calculations in development don't particularly matter. See this issue: https://github.com/webpack/webpack-dev-server/issues/377

**Comment by SethDavenport** [comment]
@watrool can you make this change then?

if process.NODE_ENV === PRODUCTION, use chunkhash, otherwise use hash-id?

**Comment by smithad15** [comment]
I would remove the hash completely for dev

**Comment by troyt-42** [comment]
@SethDavenport @smithad15 Please see https://github.com/rangle/angular2-starter/pull/182 :)
