### ISSUE TITLE
update angular 2 dependency to 2.0.0-beta.10

### ISSUE THREAD

**Issue by nexus-uw** [rangle/rangle-starter#61]
new version was released earlier today,
https://github.com/angular/angular/commit/3bd87147ab2c9aeb6683e506895fd0c8b931fb9d

**Comment by SethDavenport** [comment]
@JaKXz any idea why Greenkeeper didn't pick up on this?

**Comment by JaKXz** [comment]
Probably because it's not a typical versioning scheme - technically, the version number hasn't changed.

Also, I was looking at the [release notes](https://github.com/angular/angular/blob/master/CHANGELOG.md#200-beta10-2016-03-17) last night and it might be time for that zone.js upgrade as well? (e.g. rangle/angular2-redux-starter#74)

**Comment by SethDavenport** [comment]
Well need to use whatever zonejs angular2 beta10 depends on.

**Comment by JaKXz** [comment]
Had some fun debugging this with @nexus-uw, looks like angular/angular#7655 and angular/angular#7657 need to be merged since this build is broken.

**Comment by JaKXz** [comment]
Closing in favour of `beta11`, and the ideal will be when [angular2 has more coverage of basic TS compilation](https://github.com/angular/angular/issues/7656#issuecomment-198413877).
