### ISSUE TITLE
CSS Issues on IE9

### ISSUE THREAD

**Issue by SethDavenport** [rangle/rangle-starter#64]
CSS is screwy on IE9: the header bar covers the content below it and the nav items all show up on their own lines.

**Comment by SethDavenport** [comment]
This applies to the sample app in the ng starters, which are still using the old CSS.
The react ones are in better shape but still have the nav items one-per-line.

**Comment by riavalon** [comment]
It's looking like the CSS issues are due to ie9 not supporting Flexbox at all. I looked around for a polyfill that could bring support for it in but unfortunately it doesn't seem there are any effective polyfills that are compliant with the current flexbox spec.

See [this article for more details about flexbox support in old IE](https://www.bhalash.com/archives/13544804709)

Will probably have to find an alternative way to support layout in < IE9

**Comment by BrendanFDMoore** [comment]
I used Flexie with lukewarm results on a previous project. Its horribly
inefficient, though, and only mostly works. And yea getting it to look just
right side by side is not turn key.

Fun fact: it makes a redundant call to the current URL in order to gobble
up the CSS that comes with it. Yea.

**Comment by SethDavenport** [comment]
OK my bad for not checking flexbox IE support.  Sigh.

While polyfills for JS can be effective polyfills for CSS tend to be really slow and crappy. So yeah I agree that's probably not the right approach.

I guess we should look to see how hard it would be to do the CSS without flex box.

**Comment by gillianml** [comment]
@riavalon are you actively working gone this. If not, could you please remove yourself from this card?

**Comment by gillianml** [comment]
Because a designer may be available to help with this.
