### ISSUE TITLE
replace basscss with bootstrap

### ISSUE THREAD

**Issue by gadieichhorn** [rangle/rangle-starter#79]
help needed converting the CSS loader to bootstrap (any? css/sass/less) and remove the basscss default.
I am using the angular2-redux-starter. assuming this is the right base project setup for such a request.

**Comment by SethDavenport** [comment]
Hi @gadieichhorn, thanks for your note.

We don't use bootstrap much here because it's not a good fit with our design department's best practices. So I don't really have a mandate to change our master repos to use it.

That said, if you're looking to add it in to a project based on our starter, it should be possible using `bootstrap-loader` from `npm`.

In effect, you'd probably have to do the following:
1. get rid of all the basscss and postcss stuff from `package.json`
2. `npm install --save-dev bootstrap-loader`
3. Customize `webpack.config.js` according to the instructions from the [bootstrap-loader](https://www.npmjs.com/package/bootstrap-loader) team.

... and then write your `.css` files in SASS instead of CSS4.

As an aside, if you're curious about in why we chose basscss instead of bootstrap, you can take a look at our CSS strategy notes here: http://rangle.github.io/intro-to-modular-css

**Comment by gadieichhorn** [comment]
tanks @SethDavenport 
I will give that a go.
