### ISSUE TITLE
angular2-redux-starter devDependences

### ISSUE THREAD

**Issue by aralroca** [rangle/rangle-starter#88]
Well, is not an issue, is a question about **angular2-redux-starter** `devDependences`. 

Why dependences like **ramda**, **immutable**, **ng2-redux**, **redux**, **redux-thunk**, **redux-localstorage**, etc are `devDependences` in `package.json`? Aren't used in production?

**Comment by SethDavenport** [comment]
Hi @araloca - thanks for your question.

This is an ongoing dicussion right now - see rangle/rangle-starter#44.

The high-level summary is that `dependencies` are used for things which are needed to actually run the starter; so for example anything actively used by the express server.

The client side libraries you mention are only used explicitly when we build the client - relevant parts of them are pulled in by the webpack bundling logic prior to deployment.

However it is a bit of an open question, since bundlers like webpack and browserify blur the line between the two types of dependency somewhat.

**Comment by SethDavenport** [comment]
If you disagree, feel free to contribute to the discussion on issue rangle/rangle-starter#44.
