### ISSUE TITLE
Babel coverage numbers not correct

### ISSUE THREAD

**Issue by SethDavenport** [rangle/rangle-starter#92]
The only include files that are tested!

**Comment by SethDavenport** [comment]
Note this likely a config issue, not related to the coverage plugin.  The typescript repos have the same problem.

**Comment by clbond** [comment]
This has been fixed now in these PRs: https://github.com/rangle/angular-redux-starter/pull/135, https://github.com/rangle/angular2-redux-starter/pull/180, https://github.com/rangle/angular2-starter/pull/54

**Comment by SethDavenport** [comment]
Cool - so what remains is the two react starters with their non-karma toolchains, right?

**Comment by clbond** [comment]
Yes, that's correct. typescript-react-redux-starter has no code coverage report at all. react-redux-starter does have a code coverage report but it is incorrect because it omits files that are not part of the test dependency tree. But at this point all of the TypeScript-based starters have correct code coverage reports.
