### ISSUE TITLE
Add linting to unit tests

### ISSUE THREAD

**Issue by BrendanFDMoore** [rangle/rangle-starter#94]
Currently, only `ts-react` has the linting rules applied to the test files. We should probably add this for all starters.

**Comment by codebyuma** [comment]
We dug into this a bit - the ts-react project's front-end tests are actually being linted simply because they are in the src folder and not because they are explicitly called out in the package.json.

Original assumption was that the tests were only being linted because of the inclusion of the `test/` folder in this line:

`"lint-ts": "tslint 'src/**/*.tsx' 'src/**/*.ts' 'test/**/*.tsx' 'test/**/*.ts'"`

I'm going to review the rest of the starters anyway to confirm that all tests are linted (regardless of where they live in the project)

**Comment by codebyuma** [comment]
@BrendanFDMoore  @SethDavenport Just to confirm: so far, of the starters I've checked, the tests are linted before they are run ( `npm run test`) and when we explicitly run linting (`npm run lint`). Do we also want them to be linted before we build ( ie `npm run build`)? I'm not sure what the benefit is of linting the test files at that point but thought I'd confirm.

**Comment by SethDavenport** [comment]
@codebyuma the tests should live with the code that they test in all the starters - this is Rangle.io practice. It makes it easier to grok if you keep all the parts of a thing together.

So there shouldn't really be a need to have separate src and test linting rules - src/*_/_.ts should do the trick.

This should definitely happen for `npm test` because we want any lint error anywhere to fail CI.

For `npm run build` I tend to think we should lint everything but tests are less of a concern there.  They may be getting left out because of the prod webpack config excluding .test.ts files.  If so, that's fine.

**Comment by codebyuma** [comment]
Ok, all the starters do lint the tests when running `npm run lint` and `npm run test`. They all also seem to exclude the tests when linting during `npm run build`.

**Comment by codebyuma** [comment]
Just an update: 
- All of the starters lint both test and src code when you  `npm run lint` and `npm run test`
- All of the starters lint everything except the tests when you `npm run build` 
- But only React Redux Starter stops the build if linting fails. The other ones just show warnings if there are linting errors.

@SethDavenport should they all stop the build if linting fails?

**Comment by SethDavenport** [comment]
The requirement here is that `npm test` should fail CI if there are lint errors.

So introduce a lint error and run

`npm run lint` or `npm test`

Then see what it returned using `echo $?`: it should be non zero if there are linter errors, 0 otherwise.

**Comment by codebyuma** [comment]
Ok in that case, there isn't anything to be done here. All five starters produce linter errors for both test and non-test code.
