### ISSUE TITLE
angular2-redux-starter - newbie suggestion & question

### ISSUE THREAD

**Issue by vespertilian** [rangle/rangle-starter#97]
Hi, 

I attended you online Angular 2 course this week and was just testing out some of the things I learnt. Via your angular 2 redux starter repo. 

One of the first things I was interested in understanding was how a user input value, not just a click event, would flow through an Angular 2 Redux app. So I figured I would extend the counter so you could click a button and have the count increase by an arbitrary number. 

I feel this scenario would be worthwhile to include as a sample for other students / newbies, both in your git book and in you base app, it's a common use case. As a newbie it took me a while to work out.

This is what I ended up implementing in the Redux section, I have omitted the bindings to the view as it's covered by generic Angular tutorials. 

Action:

``` js
// actions/counter.ts
export function incrementBy(incrementBy) {
  return {
    type: INCREMENT_COUNTER_BY,
    incrementBy: incrementBy
  };
}
```

Reducer: 

``` js
// reducers/counter.ts
...
    case INCREMENT_COUNTER_BY:
      return state.update('count', (value) => {
          return value + action.incrementBy;
      });
```

I then tried to write a test copying you samples, and this is where the question comes. 

``` js

  // counter.test.ts
  describe.only('on INCREMENT_COUNTER_BY', () => {
    it('should increment state.count using the incrementBy value', () => {
      const previousValue = state.get('count');
      state = fireAction(
        counterReducer, 
        state, 
        INCREMENT_COUNTER_BY, 
        5);
      assert.strictEqual(state.get('count'), previousValue + 5);
    });
  });
```

This did not work as the fireAction function maps to a `payload` object key. Where I was using `incrementBy` as a key on my action.  

``` js
/**
 * Used for testing to fire actions against a reducer.
 *
 * @param {Function} reducer Reducer to test
 * @param {Object} currentState The current state of the reducer
 * @param {String} type The action type to fire
 * @param {Object} payload The payload (optional) to fire
 * @return {Object} Updated state as a result of the action
 */
export default function fireAction(reducer, currentState, type, payload = {}) {
  return reducer(currentState, {
    type,
    payload,
  });
}
```

So my question: You use payload in your fireAction function. Is this Redux best practice? Should I only have `type: NAME, payload: 5` as the action. vs `type: NAME, incrementBy: 5, someOtherVal: 2` etc. Maybe I implemented the action poorly is there a better way? 

Any help would be appreciated and I feel an example in this area would help future students. 

Happy to try a pull request to your book, after I get my head around it if you like?

**Comment by kosz** [comment]
@ vespertilian payload is indeed a convention. I'm not sure if it's official in Redux, but it's a pretty good convention and the fireAction is coded using it. 

It can be indeed confusing when writing your action/reducer without using payload, because many Redux docs/examples don't use it, and then fireAction expecting it when you write your test. 

You can either change the way fireAction works in your code, or use the payload convention.

``` js
type: NAME, 
payload: { 
  incrementBy: 5,
  someOtherVal:2
}
```

**Comment by BrendanFDMoore** [comment]
Hi @vespertilian - what @kosz  said is correct. While the use of `payload` is not strict (see some example not using it in the [Redux documentation](http://redux.js.org/docs/basics/Actions.html)), it has become something of a community convention. You can certainly modify `fireAction` to handle whatever structure you like, but we prefer to keep a common structure to avoid writing customized functions:

``` js
export default function fireAction(reducer, currentState, type, payload = {}) {
  return reducer(currentState, {
    type,
    payload,
  });
}
```

In order to accomplish this with minimal changes, I suggest changing your action creator to pack your `incrementBy` parameter inside the `payload` as an object. This pays off even further in simplicity when you want to carry multiple parameters:

``` js
export function incrementBy(value = 1, negative = false) {
  return {
    type: INCREMENT_COUNTER_BY,
    payload: {
      incrementBy: value,
      negative: (negative === true),
    },
  };
}
```

and in your reducer you can just pluck off the parameters you want from within the payload object:

``` js
case INCREMENT_COUNTER_BY:
    return state.update('count', (value) => value + (action.payload.incrementBy)*(action.payload.negative ? -1 : 1));
```

And you can write tests which construct a `payload` to pass into `fireAction`:

`````` js
describe('on INCREMENT_COUNTER_BY', () => {
    it('should increment state.count by 7', () => {
      const previousValue = state.get('count');
      state = fireAction(counterReducer, state, INCREMENT_COUNTER_BY, {incrementBy: 7, negative: false});
      assert.strictEqual(state.get('count'), previousValue + 7);
    });

    it('should decrement state.count by 13', () => {
      const previousValue = state.get('count');
      state = fireAction(counterReducer, state, INCREMENT_COUNTER_BY, {incrementBy: 13, negative: true});
      assert.strictEqual(state.get('count'), previousValue - 13);
    });
  });
```js
``````

**Comment by vespertilian** [comment]
@kosz @BrendanFDMoore.

Yep, that's crystal clear. I'm very keen to use convention where possible. 

Thanks!

**Comment by BrendanFDMoore** [comment]
No problem @vespertilian - glad it was helpful.

If you're interested, I've pushed my complete worked example here: https://github.com/BrendanFDMoore/angular2-redux-starter/tree/increment-by

Cheers,
-Brendan
